/**
 * This file is autogenerated by Scaffold-Alchemy.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-alchemy/contract";

const deployedContracts = {
  11155111: {
    EscrowFactory: {
      address: "0x94a59d6f0ddcd6986598bc7b5aa2529eb29bd4e5",
      abi: [
        {
          type: "event",
          name: "EscrowCreated",
          inputs: [
            {
              name: "escrowAddress",
              type: "address",
              baseType: "address",
              indexed: true,
              components: null,
              arrayLength: null,
              arrayChildren: null,
            },
            {
              name: "payer",
              type: "address",
              baseType: "address",
              indexed: true,
              components: null,
              arrayLength: null,
              arrayChildren: null,
            },
            {
              name: "payee",
              type: "address",
              baseType: "address",
              indexed: true,
              components: null,
              arrayLength: null,
              arrayChildren: null,
            },
            {
              name: "amount",
              type: "uint256",
              baseType: "uint256",
              indexed: false,
              components: null,
              arrayLength: null,
              arrayChildren: null,
            },
            {
              name: "expiration",
              type: "uint256",
              baseType: "uint256",
              indexed: false,
              components: null,
              arrayLength: null,
              arrayChildren: null,
            },
          ],
          outputs: [],
        },
        {
          type: "function",
          name: "createEscrow",
          stateMutability: "payable",
          inputs: [
            {
              name: "_payee",
              type: "address",
              baseType: "address",
              components: null,
              arrayLength: null,
              arrayChildren: null,
            },
            {
              name: "_duration",
              type: "uint256",
              baseType: "uint256",
              components: null,
              arrayLength: null,
              arrayChildren: null,
            },
          ],
          outputs: [
            {
              name: "escrow",
              type: "address",
              baseType: "address",
              components: null,
              arrayLength: null,
              arrayChildren: null,
            },
          ],
        },
        {
          type: "function",
          name: "escrows",
          stateMutability: "view",
          inputs: [
            {
              name: "",
              type: "uint256",
              baseType: "uint256",
              components: null,
              arrayLength: null,
              arrayChildren: null,
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              baseType: "address",
              components: null,
              arrayLength: null,
              arrayChildren: null,
            },
          ],
        },
        {
          type: "function",
          name: "getEscrows",
          stateMutability: "view",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address[]",
              baseType: "array",
              components: null,
              arrayLength: -1,
              arrayChildren: {
                name: "",
                type: "address",
                baseType: "address",
                components: null,
                arrayLength: null,
                arrayChildren: null,
              },
            },
          ],
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
